# Generated by Django 5.1.1 on 2024-11-28 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_medicos_crm_alter_medicos_especialidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exame', models.CharField(max_length=100)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('resultados', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.consultas')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pacientes')),
            ],
        ),
    ]
